version: "3.4"
services:
    proxy-service:
        ports:
            - "5000:80"
            - "5010:9901"
        environment:
            - ENVOY_UI_SERVICE_ADDRESS=ui-service
            - ENVOY_UI_SERVICE_PORT=80

    ui-service:
        ports:
            - "5100:80"
        environment:
            - PORT=80
            - STATIC_FILES_DIR=./static
