version: "3.4"
services:
    rabbitmq:
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq:/var/lib/rabbitmq
            - rabbitmq-logs:/var/log/rabbitmq

    db:
        environment:
            POSTGRES_USER: "pguser"
            POSTGRES_PASSWORD: "pgpassword"
            POSTGRES_DB: "db"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    proxy-service:
        ports:
            - "5000:80"
            - "5010:9901"
        environment:
            - ENVOY_UI_SERVICE_ADDRESS=ui-service
            - ENVOY_UI_SERVICE_PORT=80

    ui-service:
        ports:
            - "5100:80"
        environment:
            - PORT=80
            - STATIC_FILES_DIR=./static
