version: '3.4'
services:
  proxy-service:
    build:
      context: services/Proxy
      dockerfile: Dockerfile
    networks:
      - services_network

  ui-service:
    build:
      context: services/UI
      dockerfile: Dockerfile
    networks:
      - services_network

networks:
  services_network:
    external: true
