admin:
    address:
        socket_address:
            address: 0.0.0.0
            port_value: 9901
static_resources:
    listeners:
        - address:
              socket_address:
                  address: 0.0.0.0
                  port_value: 80
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          stat_prefix: ingress_http
                          use_remote_address: true
                          codec_type: AUTO
                          route_config:
                              name: local_route

                              response_headers_to_remove:
                                  - X-Powered-By
                              response_headers_to_add:
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: Content-Security-Policy
                                        value: "default-src 'self'; base-uri 'self'; font-src 'self' https: data:; form-action 'self'; frame-ancestors 'self'; img-src 'self' data:; object-src 'none'; script-src 'self'; script-src-attr 'none'; style-src 'self' https: 'unsafe-inline'; upgrade-insecure-requests"
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: Cross-Origin-Opener-Policy
                                        value: same-origin
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: Cross-Origin-Resource-Policy
                                        value: same-origin
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                          key: Origin-Agent-Cluster
                                          value: ?1
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: Referrer-Policy
                                        value: strict-origin-when-cross-origin
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: Strict-Transport-Security
                                        value: "max-age=15552000; includeSubDomains"
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: X-Content-Type-Options
                                        value: nosniff
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: X-Frame-Options
                                        value: DENY
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                          key: X-Permitted-Cross-Domain-Policies
                                          value: none
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: X-XSS-Protection
                                        value: "0"

                              virtual_hosts:
                                  - name: virtual_host
                                    domains:
                                        - '*'
                                    routes:
                                        - match:
                                              prefix: /auth
                                          route:
                                              cluster: authentication-service
                                          typed_per_filter_config:
                                              envoy.filters.http.ext_authz:
                                                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                                                  disabled: true

                                        - match:
                                              prefix: /graphql
                                          route:
                                              cluster: stitching-service

                                        - match:
                                              prefix: /
                                          route:
                                              cluster: ui-service
                                          typed_per_filter_config:
                                              envoy.filters.http.ext_authz:
                                                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                                                  disabled: true
                          http_filters:
                              - name: envoy.filters.http.ext_authz
                                typed_config:
                                    '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                                    transport_api_version: V3
                                    clear_route_cache: true
                                    allowed_headers:
                                        patterns:
                                            - exact: authorization
                                              ignore_case: true
                                    http_service:
                                        path_prefix: /auth/authorize
                                        authorization_request:
                                            headers_to_add:
                                                - key: content-type
                                                  value: text/plain
                                        authorization_response:
                                            allowed_upstream_headers:
                                                patterns:
                                                    - exact: authorization
                                                      ignore_case: true
                                        server_uri:
                                            uri: 'http://${AUTHENTICATION_SERVICE_ADDRESS}:${AUTHENTICATION_SERVICE_PORT}'
                                            cluster: authentication-service
                                            timeout: 10s

                              - name: envoy.filters.http.router
                                typed_config:
                                    '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    clusters:
        - name: ui-service
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: ui-service
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${UI_SERVICE_ADDRESS}'
                                      port_value: '${UI_SERVICE_PORT}'

        - name: authentication-service
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: authentication-service
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${AUTHENTICATION_SERVICE_ADDRESS}'
                                      port_value: '${AUTHENTICATION_SERVICE_PORT}'

        -   name: stitching-service
            connect_timeout: 5s
            type: STRICT_DNS
            lb_policy: ROUND_ROBIN
            load_assignment:
                cluster_name: stitching-service
                endpoints:
                    -   lb_endpoints:
                            -   endpoint:
                                    address:
                                        socket_address:
                                            address: '${STITCHING_SERVICE_ADDRESS}'
                                            port_value: '${STITCHING_SERVICE_PORT}'
