name: Build services

on:
    push:
        branches: ["main"]
        paths:
            - "services/**"

    pull_request:
        types: [opened, synchronize, reopened]
        branches: ["main"]
        paths:
            - "services/**"
            - ".github/workflows/service.*.yml"
            - ".github/workflows/services.*.yml"

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        strategy:
            matrix:
                service:
                    - { name: 'frontend', directory: 'services/Frontend' }
                    - { name: 'backend', directory: 'services/Backend' }
                    - { name: 'gateway', directory: 'services/Gateway' }

        uses: ./.github/workflows/service.build.yml
        with:
            image-tag: "latest" # TODO: Right now we don't need tags other than "latest", but they could be necessary in the future
            service-directory: ${{ matrix.service.directory }}
            service-name: ${{ matrix.service.name }}
        secrets:
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN  }}
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            PACKAGES_REGISTRY_PAT: ${{ secrets.PACKAGES_REGISTRY_PAT }}
