name: Build services

on:
    push:
        branches: ["main"]
        paths:
            - "services/**"

    pull_request:
        types: [opened, synchronize, reopened]
        branches: ["main"]
        paths:
            - "services/**"
            - ".github/workflows/service.*.yml"
            - ".github/workflows/services.*.yml"

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        strategy:
            matrix:
                service:
                    - { name: 'frontend', directory: 'services/Frontend', image-repository: "hejs22/codename-frontend" }
                    - { name: 'backend', directory: 'services/Backend', image-repository: "hejs22/codename-backend" }
                    - { name: 'gateway', directory: 'services/Gateway', image-repository: "hejs22/codename-gateway" }
                    - { name: 'mail-service', directory: 'services/MailService', image-repository: "hejs22/codename-mail-service" }
                    - { name: 'journal-service', directory: 'services/JournalService', image-repository: "hejs22/codename-journal-service" }
                    - { name: 'identity-service', directory: 'services/IdentityService', image-repository: "hejs22/codename-identity-service" }
                    - { name: 'alert-service', directory: 'services/AlertService', image-repository: "hejs22/codename-alert-service" }
                    - { name: 'user-service', directory: 'services/UserService', image-repository: "hejs22/codename-user-service" }

        uses: ./.github/workflows/service.build.yml
        with:
            service-image-tag: ${{ github.event.number == 0 && 'latest' ||  format('pr-{0}', github.event.pull_request.number)  }}
            service-directory: ${{ matrix.service.directory }}
            service-name: ${{ matrix.service.name }}
            service-image-repository: ${{ matrix.service.image-repository }}
        secrets:
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN  }}
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            PACKAGES_REGISTRY_PAT: ${{ secrets.PACKAGES_REGISTRY_PAT }}
